# MCP Server Configuration - Production Template
# Generated on: 2024-01-15 10:30:00
# File: production.yaml

# Production environment configuration optimized for:
# - Production deployment
# - Security hardening
# - Performance optimization
# - Comprehensive logging
# - Resource efficiency

server:
  host: 0.0.0.0
  port: 8080
  max_connections: 100
  timeout: 30
  ssl:
    enabled: true
    cert_file: /etc/ssl/certs/mcp-server.crt
    key_file: /etc/ssl/private/mcp-server.key

database:
  path: /var/lib/mcp-server/mcp_server.db
  pool_size: 10
  timeout: 10
  backup:
    enabled: true
    interval: 86400  # 24 hours
    retention: 7

search:
  engine: whoosh
  index_directory: /var/lib/mcp-server/search_index
  field_weights:
    endpoint_path: 1.5
    summary: 1.2
    description: 1.0
    parameters: 0.8
    tags: 0.6
  performance:
    cache_size_mb: 128
    max_results: 1000
    search_timeout: 10

logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: /var/log/mcp-server/server.log
  rotation:
    enabled: true
    max_size_mb: 10
    backup_count: 5

features:
  metrics:
    enabled: true
    endpoint: /metrics
  health_check:
    enabled: true
    endpoint: /health
  rate_limiting:
    enabled: true
    requests_per_minute: 100